### ISSUE TITLE
RQ-13: Implement Alert Box showing notification details - Alerts/Notifcations

### ISSUE THREAD

**Issue by oneuptim** [oneuptim/rentalQ#31]
When user clicks on an alert, it should have an alert box/modal pop up with the full detail information about the alert and instructions to complete it.

**Expected**
It should show an alert box with details about the notification.

**Comment by oneuptim** [comment]
➤ russell commented:

deb can you see if this works on your phone not working at all on mine

**Comment by oneuptim** [comment]
➤ Deb commented:

Alert section is empty on my phone.

**Comment by oneuptim** [comment]
➤ Tim Maina commented:

[Deb](https://app.asana.com/0/386369535005044/386369535005044) are you using the test account on your phone or the account you created?

**Comment by RentalQ** [comment]
using a gmail account not the jack@test account -

**Comment by oneuptim** [comment]
➤ Tim Maina commented:

Ok, that's why. I'll send an alert to your account. Those alerts on the demo all go to the test account. How about you [russell](https://app.asana.com/0/386356730444209/386356730444209), do you use the test account or your own account?

**Comment by RentalQ** [comment]
are we talking about the app or agent portal? im using my own account for tenant app, jack@ for agent portal

**Comment by oneuptim** [comment]
➤ Deb commented:

I'm using a gmail account for the app and I'm using [jack@test.com](mailto:jack@test.com) for the agent view.  Let me know if I need to change this though.  Thanks!

**Comment by oneuptim** [comment]
➤ russell commented:

Bug  - dont know if its due to the amount of notes i have added to my profile or due to me adding a large note but i had to log out of app and back in for the alerts to come into my phone

**Comment by oneuptim** [comment]
➤ Tim Maina commented:

[russell](https://app.asana.com/0/386356730444209/386356730444209)[Deb](https://app.asana.com/0/386369535005044/386369535005044) this is done, please test.

**Comment by oneuptim** [comment]
➤ russell commented:

testing done and works well

**Comment by oneuptim** [comment]
➤ Deb commented:

tested too (sorry bit late in testing though!).  I received the alerts
